### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by bvogel** [yolk/mite-rb#9]
Hi,

mite won't work with rails 5 due to the activeresource dependency which hasn't been released for rails 5.

**Comment by yolk** [comment]
Hi Burkhard,

it seems as if activeresource 5 is not released on rubygems yet; but you could try to depend on the current version from github instead, which claims to work with rails 5. Could you try to add the following to your Gemfile:

    gem 'activeresource', github: 'rails/activeresource'

Let me know if this solved your issue. Thanks.
